name: Release

on:
  push:
    tags:
    - '*'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    outputs:
      MOD_VERSION: ${{ steps.metadata.outputs.MOD_VERSION }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Extract metadata
      id: metadata
      run: |
        MOD_VERSION=$(jq -r '.Version' huHU/manifest.json)
        echo "MOD_VERSION=$MOD_VERSION" >> "$GITHUB_OUTPUT"

        TAG_NAME="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
        git tag -l --format='%(contents)' "$TAG_NAME" > changelog.txt

    - name: Create ZIP archive
      run: zip -qq -r TimberHUN.zip huHU

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          changelog.txt
          TimberHUN.zip

  github_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: TimberHUN.zip
        bodyFile: changelog.txt

  modio_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - uses: nickelc/upload-to-modio@v2
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: 3659
        mod: 4960361
        version: ${{ needs.prepare_release.outputs.MOD_VERSION }}
        changelog-path: changelog.txt
        path: TimberHUN.zip

  steam_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - name: Prepare Steam changelog
      run: |
        {
          echo 'CHANGELOG<<__EOF__'
          cat changelog.txt
          echo '__EOF__'
        } >> "$GITHUB_ENV"
    - uses: AnarkisGaming/workshop@v1
      with:
        appID: 1062090
        publishedFileID: 3486799229
        path: huHU
        changelog: ${{ env.CHANGELOG }}
      env:
        STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_ACCOUNT_NAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
