name: Release

on:
  push:
    tags:
    - '*'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    outputs:
      GAME_ID: ${{ steps.metadata.outputs.GAME_ID }}
      MOD_ID: ${{ steps.metadata.outputs.MOD_ID }}
      MOD_VERSION: ${{ steps.metadata.outputs.MOD_VERSION }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Extract mod.io metadata
      id: metadata
      run: |
        GAME_ID=$(jq -r '.modIo.game' huHU/manifest.json)
        echo "GAME_ID=$GAME_ID" >> "$GITHUB_OUTPUT"

        MOD_ID=$(jq -r '.modIo.mod' huHU/manifest.json)
        echo "MOD_ID=$MOD_ID" >> "$GITHUB_OUTPUT"

        MOD_VERSION=$(jq -r '.Version' huHU/manifest.json)
        echo "MOD_VERSION=$MOD_VERSION" >> "$GITHUB_OUTPUT"

        TAG_NAME="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
        git tag -l --format='%(contents)' "$TAG_NAME" > changelog.txt

    - name: Create ZIP archive
      run: zip -qq -r TimberHUN.zip huHU

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          changelog.txt
          TimberHUN.zip

  github_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: TimberHUN.zip
        skipIfReleaseExists: true
        bodyFile: changelog.txt

  modio_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - uses: nickelc/upload-to-modio@v2
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: ${{ needs.prepare_release.outputs.GAME_ID }}
        mod: ${{ needs.prepare_release.outputs.MOD_ID }}
        version: ${{ needs.prepare_release.outputs.MOD_VERSION }}
        changelog-path: changelog.txt
        path: TimberHUN.zip

  steam_release:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        name: release-artifacts
        path: .
    - name: Prepare Steam changelog
      run: |
        CHANGELOG=$(tr '\n' '\\n' < changelog.txt)
        echo "CHANGELOG=$CHANGELOG" >> "$GITHUB_ENV"
    - uses: AnarkisGaming/workshop@v1
      with:
        appID: 1062090
        publishedFileID: 3486799229
        path: huHU
        changelog: ${{ env.CHANGELOG }}
      env:
        STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_ACCOUNT_NAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
